# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
