services:
  db:
    image: mysql:8.0
    container_name: lomarket_db
    restart: always
    environment:
      MYSQL_DATABASE: lomarket
      MYSQL_ROOT_PASSWORD: nguyenminhtri
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: lomarket_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: always
    # Thay <YOUR_TUNNEL_TOKEN> bằng mã token bạn lấy trên trang Zero Trust
    command: tunnel --no-autoupdate run --token eyJhIjoiOWMyMzg2ZTAzZjRmNzMzNzQxZTFlZjU4NjU0YWY2YTQiLCJ0IjoiYjE4ODJiMzEtZTNiZC00YTMwLTg1MjQtNGQ2YzRjNGUwOWE5IiwicyI6IlpHWTFPV0l5TlRJdE0ySmhNeTAwTVdRMExUaGxNMkl0WTJabE1qWmpOVFF4WWprMiJ9
    depends_on:
      - web

volumes:
  mysql_data:
